version: 2.1
orbs:
  docker: circleci/docker@0.5.19
  deploy: pennlabs/deploy@0.0.1

branch-filters: &branch-filters
  filters:
    branches:
      only:
        - master
        - staging

jobs:
  test:
    working_directory: ~/pennlabs
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: |
            npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: |
            npm run lint

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - docker/publish:
          requires:
            - test
          cache_from: "pennlabs/image-name:latest"
          image: pennlabs/image-name
          tag: "${CIRCLE_SHA1},latest"
          context: docker-publish
          <<: *branch-filters
      - deploy/deploy:
          requires:
            - docker/publish
          context: k8s-deploy
          <<: *branch-filters
