deploy_version: 0.1.15
image_tag: latest

applications:
  - name: react
    image: pennlabs/image-name
    secret: example
    ingress:
      hosts:
        - host: example.com
          paths: ["/"]
    extraEnv:
      - name: PORT
        value: 80
